name: Deploy to Google Apps Script

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Decode and set clasp credentials
        run: |
          echo "${{ secrets.CLASP_CREDENTIALS }}" | base64 -d > ~/.clasprc.json

      - name: Push to Apps Script
        run: |
          clasp push
